# Generated by Django 4.0.4 on 2022-06-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reference_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
