# Generated by Django 4.0.4 on 2022-06-20 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('airport_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('airport_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('plane_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('timezone_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('timezone_name', models.CharField(max_length=40)),
                ('gmt', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_time', models.DateTimeField()),
                ('leave_time', models.DateTimeField()),
                ('airport_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.arrival')),
                ('depart_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.departure')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight_number', models.CharField(max_length=6)),
                ('num_stops', models.IntegerField()),
                ('arrival_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.arrival')),
                ('depart_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.departure')),
                ('legs', models.ManyToManyField(to='flights.leg')),
                ('plane_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.plane')),
                ('stops', models.ManyToManyField(to='flights.stop')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=85)),
                ('country', models.CharField(max_length=60)),
                ('timezone_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.timezone')),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='city_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.city'),
        ),
    ]
