# Generated by Django 4.0.4 on 2022-06-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_availableseats'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stop',
            name='stop_duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
